// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// slice_sample_gamma_parameters
NumericVector slice_sample_gamma_parameters(NumericVector data, NumericVector init, NumericVector hyper, double steps, double w);
RcppExport SEXP _BTYDplus_slice_sample_gamma_parameters(SEXP dataSEXP, SEXP initSEXP, SEXP hyperSEXP, SEXP stepsSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hyper(hyperSEXP);
    Rcpp::traits::input_parameter< double >::type steps(stepsSEXP);
    Rcpp::traits::input_parameter< double >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(slice_sample_gamma_parameters(data, init, hyper, steps, w));
    return rcpp_result_gen;
END_RCPP
}
// pggg_palive
NumericVector pggg_palive(NumericVector x, NumericVector tx, NumericVector Tcal, NumericVector k, NumericVector lambda, NumericVector mu);
RcppExport SEXP _BTYDplus_pggg_palive(SEXP xSEXP, SEXP txSEXP, SEXP TcalSEXP, SEXP kSEXP, SEXP lambdaSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tcal(TcalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(pggg_palive(x, tx, Tcal, k, lambda, mu));
    return rcpp_result_gen;
END_RCPP
}
// pggg_slice_sample
NumericVector pggg_slice_sample(String what, NumericVector x, NumericVector tx, NumericVector Tcal, NumericVector litt, NumericVector k, NumericVector lambda, NumericVector mu, NumericVector tau, double t, double gamma, double r, double alpha, double s, double beta);
RcppExport SEXP _BTYDplus_pggg_slice_sample(SEXP whatSEXP, SEXP xSEXP, SEXP txSEXP, SEXP TcalSEXP, SEXP littSEXP, SEXP kSEXP, SEXP lambdaSEXP, SEXP muSEXP, SEXP tauSEXP, SEXP tSEXP, SEXP gammaSEXP, SEXP rSEXP, SEXP alphaSEXP, SEXP sSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type what(whatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tcal(TcalSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type litt(littSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type k(kSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type s(sSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(pggg_slice_sample(what, x, tx, Tcal, litt, k, lambda, mu, tau, t, gamma, r, alpha, s, beta));
    return rcpp_result_gen;
END_RCPP
}
// xbgcnbd_pmf_cpp
double xbgcnbd_pmf_cpp(NumericVector params, double t, int x, bool dropout_at_zero);
RcppExport SEXP _BTYDplus_xbgcnbd_pmf_cpp(SEXP paramsSEXP, SEXP tSEXP, SEXP xSEXP, SEXP dropout_at_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< bool >::type dropout_at_zero(dropout_at_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(xbgcnbd_pmf_cpp(params, t, x, dropout_at_zero));
    return rcpp_result_gen;
END_RCPP
}
// xbgcnbd_exp_cpp
NumericVector xbgcnbd_exp_cpp(NumericVector params, NumericVector t, bool dropout_at_zero);
RcppExport SEXP _BTYDplus_xbgcnbd_exp_cpp(SEXP paramsSEXP, SEXP tSEXP, SEXP dropout_at_zeroSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< bool >::type dropout_at_zero(dropout_at_zeroSEXP);
    rcpp_result_gen = Rcpp::wrap(xbgcnbd_exp_cpp(params, t, dropout_at_zero));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BTYDplus_slice_sample_gamma_parameters", (DL_FUNC) &_BTYDplus_slice_sample_gamma_parameters, 5},
    {"_BTYDplus_pggg_palive", (DL_FUNC) &_BTYDplus_pggg_palive, 6},
    {"_BTYDplus_pggg_slice_sample", (DL_FUNC) &_BTYDplus_pggg_slice_sample, 15},
    {"_BTYDplus_xbgcnbd_pmf_cpp", (DL_FUNC) &_BTYDplus_xbgcnbd_pmf_cpp, 4},
    {"_BTYDplus_xbgcnbd_exp_cpp", (DL_FUNC) &_BTYDplus_xbgcnbd_exp_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_BTYDplus(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
