# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slice_sample_gamma_parameters <- function(data, init, hyper, steps = 20, w = 1) {
    .Call('_BTYDplus_slice_sample_gamma_parameters', PACKAGE = 'BTYDplus', data, init, hyper, steps, w)
}

pggg_palive <- function(x, tx, Tcal, k, lambda, mu) {
    .Call('_BTYDplus_pggg_palive', PACKAGE = 'BTYDplus', x, tx, Tcal, k, lambda, mu)
}

pggg_slice_sample <- function(what, x, tx, Tcal, litt, k, lambda, mu, tau, t, gamma, r, alpha, s, beta) {
    .Call('_BTYDplus_pggg_slice_sample', PACKAGE = 'BTYDplus', what, x, tx, Tcal, litt, k, lambda, mu, tau, t, gamma, r, alpha, s, beta)
}

xbgcnbd_pmf_cpp <- function(params, t, x, dropout_at_zero = FALSE) {
    .Call('_BTYDplus_xbgcnbd_pmf_cpp', PACKAGE = 'BTYDplus', params, t, x, dropout_at_zero)
}

xbgcnbd_exp_cpp <- function(params, t, dropout_at_zero = FALSE) {
    .Call('_BTYDplus_xbgcnbd_exp_cpp', PACKAGE = 'BTYDplus', params, t, dropout_at_zero)
}

