# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slice_sample_gamma <- function(alpha, beta, lower, upper) {
    .Call('BTYDplus_slice_sample_gamma', PACKAGE = 'BTYDplus', alpha, beta, lower, upper)
}

slice_sample_mvnorm <- function(sigma) {
    .Call('BTYDplus_slice_sample_mvnorm', PACKAGE = 'BTYDplus', sigma)
}

slice_sample_gamma_parameters <- function(data, init, hyper, steps = 20, w = 1) {
    .Call('BTYDplus_slice_sample_gamma_parameters', PACKAGE = 'BTYDplus', data, init, hyper, steps, w)
}

slice_sample_ma_liu <- function(what, x, tx, Tcal, lambda, mu, r, alpha, s, beta) {
    .Call('BTYDplus_slice_sample_ma_liu', PACKAGE = 'BTYDplus', what, x, tx, Tcal, lambda, mu, r, alpha, s, beta)
}

pcnbd_palive <- function(x, tx, Tcal, k, lambda, mu) {
    .Call('BTYDplus_pcnbd_palive', PACKAGE = 'BTYDplus', x, tx, Tcal, k, lambda, mu)
}

pcnbd_slice_sample <- function(what, x, tx, Tcal, litt, k, lambda, mu, tau, t, gamma, r, alpha, s, beta) {
    .Call('BTYDplus_pcnbd_slice_sample', PACKAGE = 'BTYDplus', what, x, tx, Tcal, litt, k, lambda, mu, tau, t, gamma, r, alpha, s, beta)
}

